# This pipeline runs the terraform operations for the terraform-universaldashboard-aws repo
# Continuous Integration is disabled in AzureDevOps

parameters:
- name: terraform-operation
  type: string
  default: 'plan'
  values:
    - 'plan'
    - 'apply'
    - 'destroy'

trigger:
- none

stages:
- template: ${{variables['System.DefaultWorkingDirectory']}}/pipeline/stages.yml
  parameters:
    terraform-operation: ${{ parameters.terraform-operation}}